#
FROM quay.io/ascend/vllm-ascend:v0.18.0-a3
COPY . /root/Relax
WORKDIR /root
ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

# System dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
    build-essential patchelf tmux net-tools htop nano iputils-ping \
    autoconf automake libatlas-base-dev libgoogle-glog-dev libbz2-dev libc-ares2 \
    libleveldb-dev liblmdb-dev libprotobuf-dev libsnappy-dev libtool nasm protobuf-compiler pkg-config unzip sox\
    libsndfile1 libpng-dev libhdf5-dev gfortran rapidjson-dev ninja-build libedit-dev rsync

RUN apt-get install -y locales tzdata && \
    locale-gen "$LANG" && update-locale LANG="$LANG" LC_ALL="$LC_ALL" && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# Global config (set once, persists across subsequent RUN layers)
RUN pip config set global.index-url ${PIP_INDEX_URL} && \
    git config --global http.sslverify false && \
    git config --global http.postBuffer 2147483648

# Clone MindSpeed (mhh111 fork), Megatron-LM, MindSpeed-Bridge, Megatron-Bridge, and install
RUN git clone https://gitcode.com/ascend/MindSpeed.git /root/MindSpeed && \
    git clone https://github.com/NVIDIA/Megatron-LM.git /root/Megatron-LM && \
	git clone https://gitcode.com/ascend/MindSpeed-Bridge.git /root/MindSpeed-Bridge && \
    git clone https://github.com/NVIDIA-NeMo/Megatron-Bridge.git /root/Megatron-Bridge && \
    cd /root/MindSpeed && git checkout core_r0.16.0 && pip install -r requirements.txt && pip install -e . && \
    cd /root/Megatron-LM && git checkout core_v0.16.1 && pip install -e . && \
    cd /root/MindSpeed-Bridge && pip install -r requirements.txt && \
    cd /root/Megatron-Bridge && git checkout v0.3.1 && cp -r ../MindSpeed-Bridge/mindspeed_bridge ./

# Clone sglang (v0.5.10, includes transformers ~5.3.0) and sgl-kernel-npu, install
RUN git clone -b v0.5.10 https://github.com/sgl-project/sglang.git /root/sglang && \
    cd /root/sglang/python && \
    rm -rf pyproject.toml && \
    mv pyproject_npu.toml pyproject.toml && \
    pip install -v -e .[all_npu] && \
    git clone https://github.com/sgl-project/sgl-kernel-npu.git /root/sgl-kernel-npu && \
    cd /root/sgl-kernel-npu && \
    git checkout 2026.04.15.rc4 && \
    bash build.sh && \
    pip install output/*.whl && \
    cd /root/Relax && pip install -r requirements.txt && pip install -e .

# Install extra packages (tensordict, transferqueue, modelopt) and deep-ep symlink
RUN pip install --no-cache-dir tensordict==0.10.0 pyvers==0.1.0 --no-deps && \
    pip install "transferqueue @ git+https://github.com/redai-infra/TransferQueue.git" --no-deps && \
    pip install nvidia-modelopt && \
    pip install setuptools==79.0.1 && \
    cd "$(python3 -m pip show deep-ep | awk '/^Location:/ {print $2}')" && ln -sf deep_ep/deep_ep_cpp*.so

# Apply NPU patches
RUN cd /root/MindSpeed && \
    patch -p1 < /root/Relax/docker/npu_patch/mindspeed.patch && \
    cd /root/Megatron-Bridge && \
    patch -p1 < /root/Relax/docker/npu_patch/megatron-bridge.patch && \
    cd /root/Megatron-LM && \
    patch -p1 < /root/Relax/docker/npu_patch/megatron.patch && \
    cd /root/MindSpeed-Bridge && \
    patch -p1 < /root/Relax/docker/npu_patch/mindspeed-bridge.patch

ENV PYTHONPATH=/root/Megatron-Bridge/src:/root/MindSpeed:/root/Megatron-LM:/root/Megatron-Bridge:$PYTHONPATH

CMD ["/bin/bash"]


